// GENERATED by scripts/generate-population-ref.mjs from contracts/population-registry.json
// — do not edit by hand. Regenerate with: npm run generate:population-ref
//
// A hand edit here, or a registry change without a regeneration, FAILS
// `npm run generate:population-ref:check` (wired into `check:contracts`, so it
// runs in the PR gate). The schema and the registry cannot disagree quietly.
//
// WHAT THIS ENFORCES that a free-string `id` + independent `stage` enum does not:
// each id is pinned to the stage, parent and transform THE REGISTRY GIVES IT, so
// a real id carrying the wrong stage is rejected — not just an unknown id.
//
// See ../../contracts/population-registry.json for what each population MEANS,
// which ISL metrics land on it, and the wire labels it maps to.

import { z } from 'zod';

/** The closed stage vocabulary, from registry.stages. */
export const POPULATION_STAGES = [
  'raw',
  'transformed',
  'conditioned',
  'intervened',
] as const;
export type PopulationStage = (typeof POPULATION_STAGES)[number];

/** Every registered population id, in registry order. */
export const POPULATION_IDS = [
  'olumi.mc.model_only@1',
  'olumi.mc.auto_noise_sqrt2@1',
] as const;
export type PopulationId = (typeof POPULATION_IDS)[number];

/**
 * A reference to a registered sample population.
 *
 * Discriminated on `id`: the accepted (id, stage) pairs are exactly the pairs
 * the registry declares, and `parent_id` / `transform_id` — optional, because
 * the registry already owns the lineage — may only ever repeat the registry's
 * own values.
 */
export const PopulationRefSchema = z.discriminatedUnion('id', [
  z
    .object({
      id: z.literal('olumi.mc.model_only@1'),
      stage: z.literal('raw'),
    })
    .strict(),
  z
    .object({
      id: z.literal('olumi.mc.auto_noise_sqrt2@1'),
      stage: z.literal('transformed'),
      parent_id: z.literal('olumi.mc.model_only@1').optional(),
      transform_id: z.literal('olumi.transform.auto_scaled_noise@1').optional(),
    })
    .strict(),
]);

export type PopulationRef = z.infer<typeof PopulationRefSchema>;
