// GENERATED by scripts/generate-contract-constants.mjs — do not edit by hand.
// Regenerate with: npm run generate:contract-constants
//
// See ./health-manifest.ts for what these are and where they go.

/** sha256 of the published wire contract (package name+version + every json-schema/*.json). */
export const SCHEMA_SHA = 'e1cb720ca72d3ffe4cfc9ec1e88e188b47ac89b830fe7f98579f66f4d7acb6ff';

/** sha256 of contracts/adoption-manifest.json. */
export const CONTRACT_MANIFEST_SHA = '54608966b17eb8638a6385627303f93f490d0de8038c64ce37cadc58cdd3d078';

/** The exact @talchain/schemas version these constants were generated from. */
export const SCHEMA_PACKAGE_VERSION = '0.28.0';
